[2025-05-08 23:25:39 +0000] [8] [INFO] Starting gunicorn 23.0.0
[2025-05-08 23:25:39 +0000] [8] [INFO] Listening at: https://0.0.0.0:5000 (8)
[2025-05-08 23:25:39 +0000] [8] [INFO] Using worker: gevent
[2025-05-08 23:25:39 +0000] [27] [INFO] Booting worker with pid: 27
[2025-05-08 23:25:39 +0000] [28] [INFO] Booting worker with pid: 28
[2025-05-08 23:25:39 +0000] [29] [INFO] Booting worker with pid: 29
[2025-05-08 23:25:39 +0000] [30] [INFO] Booting worker with pid: 30
[2025-05-08 23:25:39 +0000] [31] [INFO] Booting worker with pid: 31
[2025-05-08 23:25:39 +0000] [32] [INFO] Booting worker with pid: 32
[2025-05-08 23:25:39 +0000] [33] [INFO] Booting worker with pid: 33
[2025-05-08 23:25:39 +0000] [34] [INFO] Booting worker with pid: 34
[2025-05-08 23:25:39 +0000] [35] [INFO] Booting worker with pid: 35
2025-05-08 23:25:40,314 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:25:40,314 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:25:40,314 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:25:40,314 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:25:40,332 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:25:40,467 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:25:40,467 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:25:40,467 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:25:40,467 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:25:40,468 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:25:40,468 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:25:40,468 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:25:40,468 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:25:40,478 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:25:40,480 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:25:40,598 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:25:40,598 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:25:40,598 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:25:40,598 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:25:40,605 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:25:40,637 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:25:40,638 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:25:40,638 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:25:40,638 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:25:40,649 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:25:40,714 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:25:40,714 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:25:40,715 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:25:40,715 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:25:40,720 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:25:40,761 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:25:40,761 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:25:40,761 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:25:40,761 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:25:40,766 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:25:40,810 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:25:40,810 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:25:40,811 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:25:40,811 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:25:40,816 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:25:40,915 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:25:40,915 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:25:40,915 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:25:40,915 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:25:40,920 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
[2025-05-08 23:31:27 +0000] [8] [INFO] Handling signal: term
[2025-05-08 23:31:27 +0000] [35] [INFO] Worker exiting (pid: 35)
[2025-05-08 23:35:55 +0000] [8] [INFO] Starting gunicorn 23.0.0
[2025-05-08 23:35:55 +0000] [8] [INFO] Listening at: https://0.0.0.0:5000 (8)
[2025-05-08 23:35:55 +0000] [8] [INFO] Using worker: gevent
[2025-05-08 23:35:55 +0000] [11] [INFO] Booting worker with pid: 11
[2025-05-08 23:35:55 +0000] [12] [INFO] Booting worker with pid: 12
[2025-05-08 23:35:55 +0000] [13] [INFO] Booting worker with pid: 13
[2025-05-08 23:35:55 +0000] [14] [INFO] Booting worker with pid: 14
[2025-05-08 23:35:55 +0000] [15] [INFO] Booting worker with pid: 15
[2025-05-08 23:35:55 +0000] [16] [INFO] Booting worker with pid: 16
[2025-05-08 23:35:55 +0000] [17] [INFO] Booting worker with pid: 17
[2025-05-08 23:35:55 +0000] [18] [INFO] Booting worker with pid: 18
[2025-05-08 23:35:55 +0000] [19] [INFO] Booting worker with pid: 19
2025-05-08 23:35:56,262 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:35:56,262 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:35:56,262 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:35:56,262 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:35:56,274 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:35:56,347 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:35:56,347 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:35:56,347 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:35:56,347 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:35:56,358 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:35:56,373 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:35:56,374 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:35:56,374 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:35:56,374 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:35:56,381 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:35:56,454 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:35:56,454 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:35:56,454 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:35:56,454 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:35:56,459 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:35:56,538 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:35:56,538 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:35:56,539 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:35:56,539 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:35:56,545 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:35:56,648 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:35:56,648 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:35:56,649 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:35:56,649 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:35:56,657 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:35:56,730 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:35:56,730 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:35:56,730 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:35:56,730 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:35:56,737 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:35:56,797 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:35:56,797 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:35:56,798 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:35:56,798 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:35:56,804 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:35:56,899 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:35:56,899 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:35:56,899 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:35:56,899 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:35:56,906 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
[2025-05-08 23:48:37 +0000] [8] [INFO] Starting gunicorn 23.0.0
[2025-05-08 23:48:37 +0000] [8] [INFO] Listening at: https://0.0.0.0:5000 (8)
[2025-05-08 23:48:37 +0000] [8] [INFO] Using worker: gevent
[2025-05-08 23:48:37 +0000] [11] [INFO] Booting worker with pid: 11
[2025-05-08 23:48:37 +0000] [12] [INFO] Booting worker with pid: 12
[2025-05-08 23:48:37 +0000] [13] [INFO] Booting worker with pid: 13
[2025-05-08 23:48:37 +0000] [14] [INFO] Booting worker with pid: 14
[2025-05-08 23:48:37 +0000] [15] [INFO] Booting worker with pid: 15
[2025-05-08 23:48:38 +0000] [16] [INFO] Booting worker with pid: 16
[2025-05-08 23:48:38 +0000] [17] [INFO] Booting worker with pid: 17
[2025-05-08 23:48:38 +0000] [18] [INFO] Booting worker with pid: 18
[2025-05-08 23:48:38 +0000] [19] [INFO] Booting worker with pid: 19
2025-05-08 23:48:38,643 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:48:38,643 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:48:38,643 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:48:38,643 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:48:38,650 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:48:38,663 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:48:38,663 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:48:38,664 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:48:38,664 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:48:38,683 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:48:38,776 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:48:38,777 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:48:38,777 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:48:38,777 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:48:38,784 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:48:38,874 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:48:38,875 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:48:38,875 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:48:38,875 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:48:38,883 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:48:38,892 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:48:38,893 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:48:38,893 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:48:38,893 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:48:38,898 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:48:38,983 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:48:38,983 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:48:38,983 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:48:38,984 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:48:38,993 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:48:39,049 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:48:39,049 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:48:39,049 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:48:39,049 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:48:39,057 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:48:39,132 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:48:39,132 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:48:39,132 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:48:39,132 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:48:39,137 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:48:39,195 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:48:39,195 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:48:39,195 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:48:39,195 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:48:39,199 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
[2025-05-08 23:50:28 +0000] [8] [INFO] Starting gunicorn 23.0.0
[2025-05-08 23:50:28 +0000] [8] [INFO] Listening at: https://0.0.0.0:5000 (8)
[2025-05-08 23:50:28 +0000] [8] [INFO] Using worker: gevent
[2025-05-08 23:50:28 +0000] [11] [INFO] Booting worker with pid: 11
[2025-05-08 23:50:28 +0000] [12] [INFO] Booting worker with pid: 12
[2025-05-08 23:50:28 +0000] [13] [INFO] Booting worker with pid: 13
[2025-05-08 23:50:28 +0000] [14] [INFO] Booting worker with pid: 14
[2025-05-08 23:50:28 +0000] [15] [INFO] Booting worker with pid: 15
[2025-05-08 23:50:28 +0000] [16] [INFO] Booting worker with pid: 16
[2025-05-08 23:50:28 +0000] [17] [INFO] Booting worker with pid: 17
[2025-05-08 23:50:28 +0000] [18] [INFO] Booting worker with pid: 18
[2025-05-08 23:50:28 +0000] [19] [INFO] Booting worker with pid: 19
2025-05-08 23:50:29,183 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:50:29,184 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:50:29,184 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:50:29,184 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:50:29,191 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:50:29,243 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:50:29,243 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:50:29,244 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:50:29,244 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:50:29,249 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:50:29,315 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:50:29,315 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:50:29,315 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:50:29,315 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:50:29,326 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:50:29,419 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:50:29,419 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:50:29,419 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:50:29,419 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:50:29,427 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:50:29,503 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:50:29,503 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:50:29,503 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:50:29,503 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:50:29,509 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:50:29,539 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:50:29,540 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:50:29,540 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:50:29,540 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:50:29,545 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:50:29,555 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:50:29,555 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:50:29,555 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:50:29,555 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:50:29,560 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:50:29,755 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:50:29,755 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:50:29,755 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:50:29,755 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:50:29,760 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:50:29,793 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:50:29,794 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:50:29,794 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:50:29,794 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:50:29,799 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
[2025-05-08 23:50:53 +0000] [8] [INFO] Handling signal: term
[2025-05-08 23:50:54 +0000] [11] [INFO] Worker exiting (pid: 11)
[2025-05-08 23:50:54 +0000] [12] [INFO] Worker exiting (pid: 12)
[2025-05-08 23:50:54 +0000] [13] [INFO] Worker exiting (pid: 13)
[2025-05-08 23:50:54 +0000] [14] [INFO] Worker exiting (pid: 14)
[2025-05-08 23:50:54 +0000] [15] [INFO] Worker exiting (pid: 15)
[2025-05-08 23:50:54 +0000] [16] [INFO] Worker exiting (pid: 16)
[2025-05-08 23:50:54 +0000] [17] [INFO] Worker exiting (pid: 17)
[2025-05-08 23:50:54 +0000] [18] [INFO] Worker exiting (pid: 18)
[2025-05-08 23:50:54 +0000] [19] [INFO] Worker exiting (pid: 19)
[2025-05-08 23:50:54 +0000] [8] [INFO] Shutting down: Master
[2025-05-08 23:51:42 +0000] [8] [INFO] Starting gunicorn 23.0.0
[2025-05-08 23:51:42 +0000] [8] [INFO] Listening at: https://0.0.0.0:5000 (8)
[2025-05-08 23:51:42 +0000] [8] [INFO] Using worker: gevent
[2025-05-08 23:51:42 +0000] [11] [INFO] Booting worker with pid: 11
[2025-05-08 23:51:42 +0000] [12] [INFO] Booting worker with pid: 12
[2025-05-08 23:51:42 +0000] [13] [INFO] Booting worker with pid: 13
[2025-05-08 23:51:42 +0000] [14] [INFO] Booting worker with pid: 14
[2025-05-08 23:51:42 +0000] [15] [INFO] Booting worker with pid: 15
[2025-05-08 23:51:42 +0000] [16] [INFO] Booting worker with pid: 16
[2025-05-08 23:51:42 +0000] [17] [INFO] Booting worker with pid: 17
[2025-05-08 23:51:42 +0000] [18] [INFO] Booting worker with pid: 18
[2025-05-08 23:51:42 +0000] [19] [INFO] Booting worker with pid: 19
2025-05-08 23:51:42,960 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:51:42,960 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:51:42,960 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:51:42,960 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:51:42,968 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:51:43,016 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:51:43,016 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:51:43,016 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:51:43,016 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:51:43,023 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:51:43,088 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:51:43,088 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:51:43,088 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:51:43,088 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:51:43,094 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:51:43,113 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:51:43,113 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:51:43,113 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:51:43,113 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:51:43,118 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:51:43,142 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:51:43,142 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:51:43,142 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:51:43,142 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:51:43,148 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:51:43,179 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:51:43,179 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:51:43,179 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:51:43,179 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:51:43,181 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:51:43,182 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:51:43,182 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:51:43,182 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:51:43,184 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:51:43,187 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:51:43,394 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:51:43,394 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:51:43,394 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:51:43,394 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:51:43,399 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:51:43,418 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:51:43,418 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:51:43,418 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:51:43,418 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:51:43,422 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
[2025-05-08 23:52:49 +0000] [8] [INFO] Handling signal: term
[2025-05-08 23:52:50 +0000] [11] [INFO] Worker exiting (pid: 11)
[2025-05-08 23:52:50 +0000] [12] [INFO] Worker exiting (pid: 12)
[2025-05-08 23:52:50 +0000] [13] [INFO] Worker exiting (pid: 13)
[2025-05-08 23:52:50 +0000] [14] [INFO] Worker exiting (pid: 14)
[2025-05-08 23:52:50 +0000] [15] [INFO] Worker exiting (pid: 15)
[2025-05-08 23:52:50 +0000] [17] [INFO] Worker exiting (pid: 17)
[2025-05-08 23:52:50 +0000] [16] [INFO] Worker exiting (pid: 16)
[2025-05-08 23:52:50 +0000] [18] [INFO] Worker exiting (pid: 18)
[2025-05-08 23:52:50 +0000] [19] [INFO] Worker exiting (pid: 19)
[2025-05-08 23:52:50 +0000] [8] [INFO] Shutting down: Master
[2025-05-08 23:55:04 +0000] [8] [INFO] Starting gunicorn 23.0.0
[2025-05-08 23:55:04 +0000] [8] [INFO] Listening at: https://0.0.0.0:5000 (8)
[2025-05-08 23:55:04 +0000] [8] [INFO] Using worker: gevent
[2025-05-08 23:55:04 +0000] [11] [INFO] Booting worker with pid: 11
[2025-05-08 23:55:04 +0000] [12] [INFO] Booting worker with pid: 12
[2025-05-08 23:55:04 +0000] [13] [INFO] Booting worker with pid: 13
[2025-05-08 23:55:04 +0000] [14] [INFO] Booting worker with pid: 14
[2025-05-08 23:55:04 +0000] [15] [INFO] Booting worker with pid: 15
[2025-05-08 23:55:04 +0000] [16] [INFO] Booting worker with pid: 16
[2025-05-08 23:55:04 +0000] [17] [INFO] Booting worker with pid: 17
[2025-05-08 23:55:04 +0000] [18] [INFO] Booting worker with pid: 18
[2025-05-08 23:55:04 +0000] [19] [INFO] Booting worker with pid: 19
2025-05-08 23:55:05,075 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:55:05,075 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:55:05,075 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:55:05,076 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:55:05,083 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:55:05,161 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:55:05,161 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:55:05,161 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:55:05,161 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:55:05,167 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:55:05,243 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:55:05,243 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:55:05,243 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:55:05,243 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:55:05,257 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:55:05,375 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:55:05,375 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:55:05,375 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:55:05,375 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:55:05,381 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:55:05,391 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:55:05,391 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:55:05,391 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:55:05,391 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:55:05,397 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:55:05,488 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:55:05,488 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:55:05,489 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:55:05,489 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:55:05,496 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:55:05,597 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:55:05,598 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:55:05,598 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:55:05,598 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:55:05,604 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:55:05,686 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:55:05,686 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:55:05,686 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:55:05,686 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:55:05,692 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:55:05,701 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:55:05,701 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:55:05,701 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:55:05,701 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:55:05,707 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
[2025-05-08 23:58:12 +0000] [8] [INFO] Starting gunicorn 23.0.0
[2025-05-08 23:58:12 +0000] [8] [INFO] Listening at: https://0.0.0.0:5000 (8)
[2025-05-08 23:58:12 +0000] [8] [INFO] Using worker: gevent
[2025-05-08 23:58:12 +0000] [11] [INFO] Booting worker with pid: 11
[2025-05-08 23:58:12 +0000] [12] [INFO] Booting worker with pid: 12
[2025-05-08 23:58:12 +0000] [13] [INFO] Booting worker with pid: 13
[2025-05-08 23:58:12 +0000] [14] [INFO] Booting worker with pid: 14
[2025-05-08 23:58:12 +0000] [15] [INFO] Booting worker with pid: 15
[2025-05-08 23:58:12 +0000] [16] [INFO] Booting worker with pid: 16
[2025-05-08 23:58:12 +0000] [17] [INFO] Booting worker with pid: 17
[2025-05-08 23:58:12 +0000] [18] [INFO] Booting worker with pid: 18
[2025-05-08 23:58:12 +0000] [19] [INFO] Booting worker with pid: 19
2025-05-08 23:58:13,000 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:58:13,000 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:58:13,000 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:58:13,000 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:58:13,010 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:58:13,112 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:58:13,112 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:58:13,112 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:58:13,112 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:58:13,125 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:58:13,239 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:58:13,239 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:58:13,239 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:58:13,239 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:58:13,246 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:58:13,317 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:58:13,318 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:58:13,318 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:58:13,318 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:58:13,324 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:58:13,343 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:58:13,343 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:58:13,343 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:58:13,343 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:58:13,353 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:58:13,392 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:58:13,392 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:58:13,392 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:58:13,392 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:58:13,399 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:58:13,420 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:58:13,420 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:58:13,420 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:58:13,420 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:58:13,426 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:58:13,459 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:58:13,459 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:58:13,459 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:58:13,459 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:58:13,464 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-08 23:58:13,643 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:58:13,643 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:58:13,643 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-08 23:58:13,643 - docker.utils.config - DEBUG - No config file found
2025-05-08 23:58:13,649 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
[2025-05-09 00:10:20 +0000] [8] [INFO] Handling signal: term
[2025-05-09 00:10:20 +0000] [11] [INFO] Worker exiting (pid: 11)
[2025-05-09 00:10:20 +0000] [12] [INFO] Worker exiting (pid: 12)
[2025-05-09 00:10:20 +0000] [13] [INFO] Worker exiting (pid: 13)
[2025-05-09 00:10:21 +0000] [15] [INFO] Worker exiting (pid: 15)
[2025-05-09 00:10:21 +0000] [16] [INFO] Worker exiting (pid: 16)
[2025-05-09 00:10:21 +0000] [17] [INFO] Worker exiting (pid: 17)
[2025-05-09 00:10:21 +0000] [14] [INFO] Worker exiting (pid: 14)
[2025-05-09 00:10:21 +0000] [18] [INFO] Worker exiting (pid: 18)
[2025-05-09 00:10:21 +0000] [19] [INFO] Worker exiting (pid: 19)
[2025-05-09 00:10:21 +0000] [8] [INFO] Shutting down: Master
[2025-05-09 00:10:24 +0000] [8] [INFO] Starting gunicorn 23.0.0
[2025-05-09 00:10:24 +0000] [8] [INFO] Listening at: https://0.0.0.0:5000 (8)
[2025-05-09 00:10:24 +0000] [8] [INFO] Using worker: gevent
[2025-05-09 00:10:24 +0000] [11] [INFO] Booting worker with pid: 11
[2025-05-09 00:10:24 +0000] [12] [INFO] Booting worker with pid: 12
[2025-05-09 00:10:24 +0000] [13] [INFO] Booting worker with pid: 13
[2025-05-09 00:10:24 +0000] [14] [INFO] Booting worker with pid: 14
[2025-05-09 00:10:24 +0000] [15] [INFO] Booting worker with pid: 15
[2025-05-09 00:10:24 +0000] [16] [INFO] Booting worker with pid: 16
[2025-05-09 00:10:24 +0000] [17] [INFO] Booting worker with pid: 17
[2025-05-09 00:10:24 +0000] [18] [INFO] Booting worker with pid: 18
[2025-05-09 00:10:24 +0000] [19] [INFO] Booting worker with pid: 19
2025-05-09 00:10:24,838 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:10:24,838 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:10:24,838 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:10:24,838 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:10:24,845 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 00:10:24,941 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:10:24,942 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:10:24,942 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:10:24,942 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:10:24,949 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 00:10:25,045 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:10:25,045 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:10:25,045 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:10:25,045 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:10:25,053 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 00:10:25,065 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:10:25,065 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:10:25,065 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:10:25,065 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:10:25,074 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 00:10:25,196 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:10:25,196 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:10:25,196 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:10:25,196 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:10:25,203 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 00:10:25,267 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:10:25,267 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:10:25,267 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:10:25,267 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:10:25,273 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 00:10:25,348 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:10:25,349 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:10:25,349 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:10:25,349 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:10:25,354 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 00:10:25,371 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:10:25,371 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:10:25,371 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:10:25,371 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:10:25,375 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 00:10:25,480 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:10:25,480 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:10:25,480 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:10:25,480 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:10:25,484 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 00:11:26,897 - root - INFO - Serving from: hosted/css, file: dashboard.css
2025-05-09 00:11:26,902 - root - INFO - Serving from: hosted/css, file: dashboard.js
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.8/dist-packages/gevent/server.py", line 209, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 120, in wrap_socket
    return self.sslsocket_class(
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 349, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 724, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1145)
2025-05-09T00:14:27Z <Greenlet at 0x7e898a8ea400: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed] at 0x7e898a80534)> failed with SSLError

2025-05-09 00:14:27,136 - root - INFO - Serving from: hosted/css, file: dashboard.css
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.8/dist-packages/gevent/server.py", line 209, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 120, in wrap_socket
    return self.sslsocket_class(
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 349, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 724, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1145)
2025-05-09T00:11:26Z <Greenlet at 0x7e898a8ea400: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed] at 0x7e898a80528)> failed with SSLError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.8/dist-packages/gevent/server.py", line 209, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 120, in wrap_socket
    return self.sslsocket_class(
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 349, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 724, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1145)
2025-05-09T00:14:23Z <Greenlet at 0x7e898a8ea400: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed] at 0x7e898a80528)> failed with SSLError

2025-05-09 00:14:27,142 - root - INFO - Serving from: hosted/css, file: dashboard.js
[2025-05-09 00:22:11 +0000] [8] [INFO] Starting gunicorn 23.0.0
[2025-05-09 00:22:11 +0000] [8] [INFO] Listening at: https://0.0.0.0:5000 (8)
[2025-05-09 00:22:11 +0000] [8] [INFO] Using worker: gevent
[2025-05-09 00:22:11 +0000] [11] [INFO] Booting worker with pid: 11
[2025-05-09 00:22:11 +0000] [12] [INFO] Booting worker with pid: 12
[2025-05-09 00:22:12 +0000] [13] [INFO] Booting worker with pid: 13
[2025-05-09 00:22:12 +0000] [14] [INFO] Booting worker with pid: 14
[2025-05-09 00:22:12 +0000] [15] [INFO] Booting worker with pid: 15
[2025-05-09 00:22:12 +0000] [16] [INFO] Booting worker with pid: 16
[2025-05-09 00:22:12 +0000] [17] [INFO] Booting worker with pid: 17
[2025-05-09 00:22:12 +0000] [18] [INFO] Booting worker with pid: 18
[2025-05-09 00:22:12 +0000] [19] [INFO] Booting worker with pid: 19
2025-05-09 00:22:12,943 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:22:12,943 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:22:12,943 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:22:12,943 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:22:12,957 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 00:22:12,960 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:22:12,960 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:22:12,960 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:22:12,961 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:22:12,973 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 00:22:12,982 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:22:12,982 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:22:12,982 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:22:12,983 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:22:12,996 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 00:22:13,054 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:22:13,054 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:22:13,054 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:22:13,054 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:22:13,065 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 00:22:13,245 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:22:13,245 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:22:13,245 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:22:13,245 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:22:13,252 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 00:22:13,289 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:22:13,289 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:22:13,289 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:22:13,289 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:22:13,297 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 00:22:13,297 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:22:13,297 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:22:13,297 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:22:13,297 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:22:13,297 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:22:13,297 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:22:13,297 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:22:13,297 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:22:13,302 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 00:22:13,302 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 00:22:13,348 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:22:13,348 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:22:13,348 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 00:22:13,348 - docker.utils.config - DEBUG - No config file found
2025-05-09 00:22:13,353 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
[2025-05-09 03:01:29 +0000] [8] [INFO] Handling signal: term
[2025-05-09 03:01:29 +0000] [17] [INFO] Worker exiting (pid: 17)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.8/dist-packages/gevent/server.py", line 209, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 120, in wrap_socket
    return self.sslsocket_class(
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 349, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 724, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1145)
2025-05-09T00:24:11Z <Greenlet at 0x7e891f141400: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed] at 0x7e891f05c28)> failed with SSLError

[2025-05-09 03:01:29 +0000] [15] [INFO] Worker exiting (pid: 15)
[2025-05-09 03:01:29 +0000] [16] [INFO] Worker exiting (pid: 16)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.8/dist-packages/gevent/server.py", line 209, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 120, in wrap_socket
    return self.sslsocket_class(
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 349, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 724, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1145)
2025-05-09T00:24:11Z <Greenlet at 0x7e891f142400: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed] at 0x7e891f05c28)> failed with SSLError

[2025-05-09 03:01:29 +0000] [19] [INFO] Worker exiting (pid: 19)
[2025-05-09 03:01:29 +0000] [12] [INFO] Worker exiting (pid: 12)
[2025-05-09 03:01:29 +0000] [11] [INFO] Worker exiting (pid: 11)
[2025-05-09 03:01:29 +0000] [13] [INFO] Worker exiting (pid: 13)
[2025-05-09 03:01:29 +0000] [14] [INFO] Worker exiting (pid: 14)
[2025-05-09 03:01:29 +0000] [18] [INFO] Worker exiting (pid: 18)
[2025-05-09 03:01:30 +0000] [8] [INFO] Shutting down: Master
[2025-05-09 03:04:19 +0000] [8] [INFO] Starting gunicorn 23.0.0
[2025-05-09 03:04:19 +0000] [8] [INFO] Listening at: https://0.0.0.0:5000 (8)
[2025-05-09 03:04:19 +0000] [8] [INFO] Using worker: gevent
[2025-05-09 03:04:19 +0000] [11] [INFO] Booting worker with pid: 11
[2025-05-09 03:04:19 +0000] [12] [INFO] Booting worker with pid: 12
[2025-05-09 03:04:19 +0000] [13] [INFO] Booting worker with pid: 13
[2025-05-09 03:04:19 +0000] [14] [INFO] Booting worker with pid: 14
[2025-05-09 03:04:19 +0000] [15] [INFO] Booting worker with pid: 15
[2025-05-09 03:04:19 +0000] [16] [INFO] Booting worker with pid: 16
[2025-05-09 03:04:19 +0000] [17] [INFO] Booting worker with pid: 17
[2025-05-09 03:04:19 +0000] [18] [INFO] Booting worker with pid: 18
[2025-05-09 03:04:19 +0000] [19] [INFO] Booting worker with pid: 19
2025-05-09 03:04:20,369 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:04:20,369 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:04:20,369 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:04:20,369 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:04:20,376 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:04:20,403 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:04:20,403 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:04:20,403 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:04:20,403 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:04:20,409 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:04:20,482 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:04:20,482 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:04:20,482 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:04:20,482 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:04:20,489 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:04:20,573 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:04:20,573 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:04:20,573 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:04:20,573 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:04:20,580 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:04:20,666 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:04:20,666 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:04:20,667 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:04:20,667 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:04:20,672 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:04:20,673 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:04:20,673 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:04:20,673 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:04:20,673 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:04:20,680 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:04:20,723 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:04:20,723 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:04:20,723 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:04:20,723 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:04:20,728 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:04:20,766 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:04:20,766 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:04:20,766 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:04:20,766 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:04:20,771 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:04:20,891 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:04:20,891 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:04:20,891 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:04:20,891 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:04:20,896 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:04:33,408 - root - INFO - Received request to generate RTMP URL.
2025-05-09 03:04:33,408 - root - INFO - Extracted eth_address: 0x4a269deba1bb61ab85d6290877309ac0cbd64e45
2025-05-09 03:04:33,408 - root - INFO - Calling API to generate secret for eth_address: 0x4a269deba1bb61ab85d6290877309ac0cbd64e45
2025-05-09 03:04:33,409 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:5003
2025-05-09 03:04:33,431 - urllib3.connectionpool - DEBUG - http://127.0.0.1:5003 "POST /generate_secret HTTP/11" 500 265
2025-05-09 03:04:33,431 - root - INFO - Secret generation API responded with status code: 500
2025-05-09 03:04:33,432 - root - ERROR - Failed to generate secret.
2025-05-09 03:04:34,804 - root - INFO - Received request to generate RTMP URL.
2025-05-09 03:04:34,805 - root - INFO - Extracted eth_address: 0x4a269deba1bb61ab85d6290877309ac0cbd64e45
2025-05-09 03:04:34,805 - root - INFO - Calling API to generate secret for eth_address: 0x4a269deba1bb61ab85d6290877309ac0cbd64e45
2025-05-09 03:04:34,806 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:5003
2025-05-09 03:04:34,810 - urllib3.connectionpool - DEBUG - http://127.0.0.1:5003 "POST /generate_secret HTTP/11" 500 265
2025-05-09 03:04:34,810 - root - INFO - Secret generation API responded with status code: 500
2025-05-09 03:04:34,810 - root - ERROR - Failed to generate secret.
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.8/dist-packages/gevent/server.py", line 209, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 120, in wrap_socket
    return self.sslsocket_class(
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 349, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 724, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1145)
2025-05-09T03:04:23Z <Greenlet at 0x71324e4fc400: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed] at 0x71324e41728)> failed with SSLError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.8/dist-packages/gevent/server.py", line 209, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 120, in wrap_socket
    return self.sslsocket_class(
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 349, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 724, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1145)
2025-05-09T03:04:30Z <Greenlet at 0x71324e4fc400: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed] at 0x71324e41728)> failed with SSLError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.8/dist-packages/gevent/server.py", line 209, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 120, in wrap_socket
    return self.sslsocket_class(
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 349, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 724, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1145)
2025-05-09T03:04:37Z <Greenlet at 0x71324e4fc400: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed] at 0x71324e41728)> failed with SSLError

2025-05-09 03:04:37,638 - root - INFO - Received request to generate RTMP URL.
2025-05-09 03:04:37,638 - root - INFO - Extracted eth_address: 0x4a269deba1bb61ab85d6290877309ac0cbd64e45
2025-05-09 03:04:37,638 - root - INFO - Calling API to generate secret for eth_address: 0x4a269deba1bb61ab85d6290877309ac0cbd64e45
2025-05-09 03:04:37,639 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:5003
2025-05-09 03:04:37,645 - urllib3.connectionpool - DEBUG - http://127.0.0.1:5003 "POST /generate_secret HTTP/11" 500 265
2025-05-09 03:04:37,646 - root - INFO - Secret generation API responded with status code: 500
2025-05-09 03:04:37,646 - root - ERROR - Failed to generate secret.
[2025-05-09 03:10:04 +0000] [8] [INFO] Starting gunicorn 23.0.0
[2025-05-09 03:10:04 +0000] [8] [INFO] Listening at: https://0.0.0.0:5000 (8)
[2025-05-09 03:10:04 +0000] [8] [INFO] Using worker: gevent
[2025-05-09 03:10:04 +0000] [11] [INFO] Booting worker with pid: 11
[2025-05-09 03:10:04 +0000] [12] [INFO] Booting worker with pid: 12
[2025-05-09 03:10:04 +0000] [13] [INFO] Booting worker with pid: 13
[2025-05-09 03:10:04 +0000] [14] [INFO] Booting worker with pid: 14
[2025-05-09 03:10:04 +0000] [15] [INFO] Booting worker with pid: 15
[2025-05-09 03:10:04 +0000] [16] [INFO] Booting worker with pid: 16
[2025-05-09 03:10:04 +0000] [17] [INFO] Booting worker with pid: 17
[2025-05-09 03:10:04 +0000] [18] [INFO] Booting worker with pid: 18
[2025-05-09 03:10:04 +0000] [19] [INFO] Booting worker with pid: 19
2025-05-09 03:10:05,238 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:10:05,238 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:10:05,238 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:10:05,238 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:10:05,246 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:10:05,281 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:10:05,281 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:10:05,281 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:10:05,281 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:10:05,291 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:10:05,422 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:10:05,422 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:10:05,422 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:10:05,422 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:10:05,431 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:10:05,456 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:10:05,456 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:10:05,456 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:10:05,457 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:10:05,468 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:10:05,541 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:10:05,541 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:10:05,541 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:10:05,541 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:10:05,547 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:10:05,600 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:10:05,600 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:10:05,600 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:10:05,600 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:10:05,607 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:10:05,653 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:10:05,653 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:10:05,653 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:10:05,653 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:10:05,658 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:10:05,810 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:10:05,810 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:10:05,810 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:10:05,810 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:10:05,815 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:10:05,874 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:10:05,875 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:10:05,875 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:10:05,875 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:10:05,879 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:10:12,848 - root - INFO - Received request to generate RTMP URL.
2025-05-09 03:10:12,849 - root - INFO - Extracted eth_address: 0x4a269deba1bb61ab85d6290877309ac0cbd64e45
2025-05-09 03:10:12,849 - root - INFO - Calling API to generate secret for eth_address: 0x4a269deba1bb61ab85d6290877309ac0cbd64e45
2025-05-09 03:10:12,850 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:5003
2025-05-09 03:10:12,867 - urllib3.connectionpool - DEBUG - http://127.0.0.1:5003 "POST /generate_secret HTTP/11" 500 265
2025-05-09 03:10:12,868 - root - INFO - Secret generation API responded with status code: 500
2025-05-09 03:10:12,868 - root - ERROR - Failed to generate secret.
[2025-05-09 03:13:30 +0000] [8] [INFO] Handling signal: term
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.8/dist-packages/gevent/server.py", line 209, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 120, in wrap_socket
    return self.sslsocket_class(
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 349, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 724, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1145)
2025-05-09T03:10:09Z <Greenlet at 0x7002473e8400: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed] at 0x70024730228)> failed with SSLError

[2025-05-09 03:13:30 +0000] [19] [INFO] Worker exiting (pid: 19)
[2025-05-09 03:13:30 +0000] [11] [INFO] Worker exiting (pid: 11)
[2025-05-09 03:13:30 +0000] [12] [INFO] Worker exiting (pid: 12)
[2025-05-09 03:13:30 +0000] [13] [INFO] Worker exiting (pid: 13)
[2025-05-09 03:13:30 +0000] [14] [INFO] Worker exiting (pid: 14)
[2025-05-09 03:13:30 +0000] [15] [INFO] Worker exiting (pid: 15)
[2025-05-09 03:13:30 +0000] [16] [INFO] Worker exiting (pid: 16)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.8/dist-packages/gevent/server.py", line 209, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 120, in wrap_socket
    return self.sslsocket_class(
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 349, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 724, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1145)
2025-05-09T03:10:11Z <Greenlet at 0x7002473e7400: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed] at 0x70024730228)> failed with SSLError

[2025-05-09 03:13:30 +0000] [17] [INFO] Worker exiting (pid: 17)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.8/dist-packages/gevent/server.py", line 209, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 120, in wrap_socket
    return self.sslsocket_class(
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 349, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 724, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1145)
2025-05-09T03:10:09Z <Greenlet at 0x7002473e7400: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed] at 0x70024730228)> failed with SSLError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.8/dist-packages/gevent/server.py", line 209, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 120, in wrap_socket
    return self.sslsocket_class(
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 349, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 724, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1145)
2025-05-09T03:10:11Z <Greenlet at 0x7002473e7400: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed] at 0x70024730228)> failed with SSLError

[2025-05-09 03:13:31 +0000] [18] [INFO] Worker exiting (pid: 18)
[2025-05-09 03:13:31 +0000] [8] [INFO] Shutting down: Master
[2025-05-09 03:13:54 +0000] [8] [INFO] Starting gunicorn 23.0.0
[2025-05-09 03:13:54 +0000] [8] [INFO] Listening at: https://0.0.0.0:5000 (8)
[2025-05-09 03:13:54 +0000] [8] [INFO] Using worker: gevent
[2025-05-09 03:13:54 +0000] [11] [INFO] Booting worker with pid: 11
[2025-05-09 03:13:54 +0000] [12] [INFO] Booting worker with pid: 12
[2025-05-09 03:13:55 +0000] [13] [INFO] Booting worker with pid: 13
[2025-05-09 03:13:55 +0000] [14] [INFO] Booting worker with pid: 14
[2025-05-09 03:13:55 +0000] [15] [INFO] Booting worker with pid: 15
[2025-05-09 03:13:55 +0000] [16] [INFO] Booting worker with pid: 16
[2025-05-09 03:13:55 +0000] [17] [INFO] Booting worker with pid: 17
[2025-05-09 03:13:55 +0000] [18] [INFO] Booting worker with pid: 18
[2025-05-09 03:13:55 +0000] [19] [INFO] Booting worker with pid: 19
2025-05-09 03:13:55,664 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:13:55,664 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:13:55,664 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:13:55,664 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:13:55,670 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:13:55,686 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:13:55,686 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:13:55,686 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:13:55,687 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:13:55,693 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:13:55,789 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:13:55,790 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:13:55,790 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:13:55,790 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:13:55,795 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:13:55,796 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:13:55,796 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:13:55,796 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:13:55,797 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:13:55,801 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:13:55,882 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:13:55,882 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:13:55,882 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:13:55,882 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:13:55,887 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:13:55,897 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:13:55,897 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:13:55,897 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:13:55,897 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:13:55,902 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:13:56,062 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:13:56,062 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:13:56,062 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:13:56,062 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:13:56,068 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:13:56,147 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:13:56,147 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:13:56,147 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:13:56,147 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:13:56,152 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:13:56,240 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:13:56,240 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:13:56,240 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:13:56,240 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:13:56,245 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.8/dist-packages/gevent/server.py", line 209, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 120, in wrap_socket
    return self.sslsocket_class(
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 349, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 724, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1145)
2025-05-09T03:14:06Z <Greenlet at 0x740bd4d29400: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed] at 0x740bd4c4428)> failed with SSLError

2025-05-09 03:14:08,410 - root - INFO - Received request to generate RTMP URL.
2025-05-09 03:14:08,410 - root - INFO - Extracted eth_address: 0x4a269deba1bb61ab85d6290877309ac0cbd64e45
2025-05-09 03:14:08,410 - root - INFO - Calling API to generate secret for eth_address: 0x4a269deba1bb61ab85d6290877309ac0cbd64e45
2025-05-09 03:14:08,411 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:5003
2025-05-09 03:14:08,417 - urllib3.connectionpool - DEBUG - http://127.0.0.1:5003 "POST /generate_secret HTTP/11" 400 43
2025-05-09 03:14:08,417 - root - INFO - Secret generation API responded with status code: 400
2025-05-09 03:14:08,417 - root - ERROR - Failed to generate secret.
[2025-05-09 03:16:11 +0000] [8] [INFO] Handling signal: term
[2025-05-09 03:16:11 +0000] [11] [INFO] Worker exiting (pid: 11)
[2025-05-09 03:16:11 +0000] [12] [INFO] Worker exiting (pid: 12)
[2025-05-09 03:16:11 +0000] [14] [INFO] Worker exiting (pid: 14)
[2025-05-09 03:16:11 +0000] [13] [INFO] Worker exiting (pid: 13)
[2025-05-09 03:16:12 +0000] [15] [INFO] Worker exiting (pid: 15)
[2025-05-09 03:16:12 +0000] [16] [INFO] Worker exiting (pid: 16)
[2025-05-09 03:16:12 +0000] [18] [INFO] Worker exiting (pid: 18)
[2025-05-09 03:16:12 +0000] [17] [INFO] Worker exiting (pid: 17)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.8/dist-packages/gevent/server.py", line 209, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 120, in wrap_socket
    return self.sslsocket_class(
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 349, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.8/dist-packages/gevent/ssl.py", line 724, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1145)
2025-05-09T03:14:06Z <Greenlet at 0x740bd4d2a400: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed] at 0x740bd4c4428)> failed with SSLError

[2025-05-09 03:16:12 +0000] [19] [INFO] Worker exiting (pid: 19)
[2025-05-09 03:16:12 +0000] [8] [INFO] Shutting down: Master
[2025-05-09 03:17:00 +0000] [8] [INFO] Starting gunicorn 23.0.0
[2025-05-09 03:17:00 +0000] [8] [INFO] Listening at: https://0.0.0.0:5000 (8)
[2025-05-09 03:17:00 +0000] [8] [INFO] Using worker: gevent
[2025-05-09 03:17:00 +0000] [11] [INFO] Booting worker with pid: 11
[2025-05-09 03:17:00 +0000] [12] [INFO] Booting worker with pid: 12
[2025-05-09 03:17:00 +0000] [13] [INFO] Booting worker with pid: 13
[2025-05-09 03:17:00 +0000] [14] [INFO] Booting worker with pid: 14
[2025-05-09 03:17:00 +0000] [15] [INFO] Booting worker with pid: 15
[2025-05-09 03:17:00 +0000] [16] [INFO] Booting worker with pid: 16
[2025-05-09 03:17:00 +0000] [17] [INFO] Booting worker with pid: 17
[2025-05-09 03:17:00 +0000] [18] [INFO] Booting worker with pid: 18
[2025-05-09 03:17:00 +0000] [19] [INFO] Booting worker with pid: 19
2025-05-09 03:17:01,591 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:17:01,592 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:17:01,592 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:17:01,593 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:17:01,609 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:17:01,673 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:17:01,674 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:17:01,674 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:17:01,674 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:17:01,688 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:17:01,721 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:17:01,721 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:17:01,721 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:17:01,721 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:17:01,729 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:17:01,779 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:17:01,780 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:17:01,780 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:17:01,780 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:17:01,787 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:17:01,793 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:17:01,793 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:17:01,793 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:17:01,793 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:17:01,800 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:17:01,830 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:17:01,830 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:17:01,830 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:17:01,830 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:17:01,837 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:17:01,895 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:17:01,895 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:17:01,895 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:17:01,895 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:17:01,900 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:17:01,971 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:17:01,971 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:17:01,971 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:17:01,971 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:17:01,976 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
2025-05-09 03:17:01,993 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:17:01,993 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:17:01,993 - docker.utils.config - DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2025-05-09 03:17:01,993 - docker.utils.config - DEBUG - No config file found
2025-05-09 03:17:01,998 - urllib3.connectionpool - DEBUG - http://localhost:None "GET /version HTTP/11" 200 824
